server:
    servlet:
      context-path: /appDSDExpConsApi
      session:
        timeout: 6000

spring: 
  profiles:
      active: 'qa'
  banner:
    location: classpath:/conf/banner.txt
      
    
logging:
  config: classpath:logback.xml 
    