spring.datasource.usr_expcons.jndi-name: jdbc/JDBCappDSDExpCons
spring.datasource.usr_sel.jndi-name: jdbc/JDBCappDSDTramiteSELApi
 
   
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      
path-file:
   vcRutaArchivoJson: /apps/dsd/registro_marcas/solicitudes/
   vcUsuario: consulta2
   vcClave: consulta2
   vcRutacmis: http://gestordoc2.indecopi.gob.pe:8080/alfresco/service/api/cmis
   vcRutaalfrcompartido: http://gestordoc2.indecopi.gob.pe:8080/share/proxy/alfresco/api/node/content/
   vcRutaalfr: Repositorio/Sites/gestor-conocimiento/documentLibrary/ResolucionesDoc
   vcRutaalfrpdf: /buscadorResoluciones/